### ISSUE TITLE
Keep crashing when running agains a cluster with gitlab running inside

### ISSUE THREAD

**Issue by riveryc** [up9inc/mizu#1089]
**Describe the bug**
This is the first time I'm using `mizu`, so trying it in a nonprod gitlab toolbox environment. 
This cluster only contains gitlab instance running in gitlab-system namespace with default gitlab components installed.
It was running ok for like a min or 2, then crashed with error in the log as following:
```
[2022-05-17T00:21:27.369+0000] INFO  ▶ setting 172.31.17.243:2379=etcd-cluster.default ▶ [1 resolver.go:178 saveResolvedName]
[2022-05-17T00:21:27.369+0000] INFO  ▶ setting 172.31.36.21=etcd-cluster.default ▶ [1 resolver.go:178 saveResolvedName]
[2022-05-17T00:21:27.369+0000] INFO  ▶ setting 172.31.36.21:2379=etcd-cluster.default ▶ [1 resolver.go:178 saveResolvedName]
[2022-05-17T00:21:27.627+0000] INFO  ▶ setting 172.31.15.87=mizu-api-server.mizu ▶ [1 resolver.go:178 saveResolvedName]
[2022-05-17T00:21:27.627+0000] INFO  ▶ setting 172.31.15.87:8899=mizu-api-server.mizu ▶ [1 resolver.go:178 saveResolvedName]
[2022-05-17T00:21:27.639+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.639+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.641+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000330): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.641+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.641+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.641+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000331): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.642+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod="gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm",container!="",pod!=""}
)
&time=1652746843.282, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.282": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.642+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod="gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm",container!="",pod!=""}
)
&time=1652746843.282, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.282": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.642+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000332): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.282": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.643+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.282&query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod="gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm",container!="",pod!=""}[120s]
  )
)
, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.282&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.643+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.282&query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod="gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm",container!="",pod!=""}[120s]
  )
)
, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.282&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.643+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000333): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.282&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-sidekiq-all-in-1-v2-69786f47f5-lnkfm\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.644+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod=~"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2",container!="",pod!=""}
)
&time=1652746843.292, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.644+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod=~"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2",container!="",pod!=""}
)
&time=1652746843.292, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.644+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000334): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.645+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2",container!="",pod!=""}[120s]
  )
)
&time=1652746843.292, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.645+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2",container!="",pod!=""}[120s]
  )
)
&time=1652746843.292, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.646+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000335): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-webservice-default-864574fbd7-bjz6x|gitlab-webservice-default-864574fbd7-x8bn2\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.292": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.646+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.315&query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod="gitlab-gitlab-pages-b5cdc49c6-ghdrg",container!="",pod!=""}[120s]
  )
)
, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.315&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.646+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.315&query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod="gitlab-gitlab-pages-b5cdc49c6-ghdrg",container!="",pod!=""}[120s]
  )
)
, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.315&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.647+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000336): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?time=1652746843.315&query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.647+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod="gitlab-gitlab-pages-b5cdc49c6-ghdrg",container!="",pod!=""}
)
&time=1652746843.315, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.315": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.647+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  container_memory_working_set_bytes{namespace="gitlab-system",pod="gitlab-gitlab-pages-b5cdc49c6-ghdrg",container!="",pod!=""}
)
&time=1652746843.315, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.315": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.647+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000337): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  container_memory_working_set_bytes{namespace=\"gitlab-system\",pod=\"gitlab-gitlab-pages-b5cdc49c6-ghdrg\",container!=\"\",pod!=\"\"}\n)\n&time=1652746843.315": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.649+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.649+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.650+0000] WARNING ▶ Failed processing entry %!d(string=000000000000000000000343): parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:181 handleHARWithSource]
[2022-05-17T00:21:27.650+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
[2022-05-17T00:21:27.650+0000] ERROR ▶ Failed to parse entry URL: http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (
  irate (
      container_cpu_usage_seconds_total{namespace="gitlab-system",pod=~"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8",container!="",pod!=""}[120s]
  )
)
&time=1652746843.256, err: parse "http://prometheus-k8s.monitoring.svc:9090/api/v1/query?query=sum by (pod,container) (\n  irate (\n      container_cpu_usage_seconds_total{namespace=\"gitlab-system\",pod=~\"gitlab-gitlab-shell-7444c568f8-7ghln|gitlab-gitlab-shell-7444c568f8-nrnk8\",container!=\"\",pod!=\"\"}[120s]\n  )\n)\n&time=1652746843.256": net/url: invalid control character in URL ▶ [1 oas_generator.go:191 getGen]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1b42fea]

goroutine 14 [running]:
github.com/up9inc/mizu/agent/pkg/oas.(*defaultOasGenerator).getGen(0xc000101310, {0xc000f59560, 0x19}, {0xc000231180, 0x12a})
	/app/agent-build/pkg/oas/oas_generator.go:197 +0x1ca
github.com/up9inc/mizu/agent/pkg/oas.(*defaultOasGenerator).handleHARWithSource(0x12f, 0xc000363b10)
	/app/agent-build/pkg/oas/oas_generator.go:172 +0x7e
github.com/up9inc/mizu/agent/pkg/oas.(*defaultOasGenerator).handleEntry(0xc0008ad000, 0xc000cf31e0)
	/app/agent-build/pkg/oas/oas_generator.go:164 +0x39d
github.com/up9inc/mizu/agent/pkg/oas.(*defaultOasGenerator).runGenerator(0xc000101310)
	/app/agent-build/pkg/oas/oas_generator.go:138 +0x4be
created by github.com/up9inc/mizu/agent/pkg/oas.(*defaultOasGenerator).Start
	/app/agent-build/pkg/oas/oas_generator.go:75 +0x25b
```

**To Reproduce**
1. Run `mizu tap -A`
2. Wait for few mins
3. Click on service map
4. See error -> service crashed, not responding
5. Refresh page, showing 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "no endpoints available for service \"mizu-api-server:80\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

6. check the log with `k logs -f -n mizu mizu-api-server -c mizu-api-server`, error message is shown as above. 

**Expected behavior**
Just normally do its job, correctly parsing things it needs to, even it cannot parse stuff, it shouldn't crash

**Logs**
cannot reproduce issue... I'll try to upload if I see one.

**Desktop (please complete the following information):**
 - OS: macOS M1
 - Web Browser: Chrome

**Comment by gadotroee** [comment]
Hi @riveryc,

I will look into this error but form what I see it happened only once and you couldn't reproduce it, I will try to reproduce it too but I do see it is related to the OAS generation so it gives me point to check exactly and I will try to update when I have some details.

**Comment by riveryc** [comment]
Thanks mate, I'll keep my eyes on it too, will post any information when I see one.
