### ISSUE TITLE
mizu tap fails with "Connection Refused" on forwarding 8899->8899 on AWS machine

### ISSUE THREAD

**Issue by ittaigilat-cx** [up9inc/mizu#1213]
**Describe the bug**
mizu tap fails to start. This is what I get when running **./mizu tap**
Waiting for Mizu Agent to start...
E0802 11:14:04.044552  313239 portforward.go:406] an error occurred forwarding 8899 -> 8899: error forwarding port 8899 to pod ff93dbe3cba2ed11b8772d16a533a415829733a8da7d45880f8eb8fb44a26447, uid : failed to execute portforward in network namespace "/var/run/netns/cni-1d86a2f5-fd35-5899-7a3e-bca1339f5139": failed to dial 8899: dial tcp4 127.0.0.1:8899: connect: connection refused
E0802 11:14:04.044842  313239 portforward.go:234] lost connection to pod
Couldn't connect to API server, for more info check logs at /home/ubuntu/.mizu/mizu_cli.log

Removing mizu resources
Error starting mizu tapper syncer: failed to get pods in ns: [default], context canceled

**To Reproduce**
./mizu tap --namespaces default --set mizu-resources-namespace=default

**Expected behavior**
mizu works correctly

**Logs**
see attached

**Screenshots**
![image](https://user-images.githubusercontent.com/66742831/182364024-0b662895-1f3f-439d-8428-89a2bf8ef5b3.png)

**Desktop (please complete the following information):**
 - OS: Linux 5.15.0-1013-aws
 - Web Browser: N/A

**Additional context**
[mizu_logs_2022_08_02__11_22_40.zip](https://github.com/up9inc/mizu/files/9241748/mizu_logs_2022_08_02__11_22_40.zip)

**Comment by mertyildiran** [comment]
@ittaigilat-cx thank you so much for reporting the issue!

When I look at the logs, I see the below error in `default.mizu-api-server.basenine.log` file:

```
2022/08/02 11:22:37 Basenine Community (Version: 0.8.3)
panic: too many open files

goroutine 1 [running]:
github.com/up9inc/basenine/server/lib.Check(...)
        /home/runner/work/basenine/basenine/server/lib/helpers.go:76
github.com/up9inc/basenine/server/lib/storages.NewNativeStorage(0x704501, 0x21, 0xc000167f38)
        /home/runner/work/basenine/basenine/server/lib/storages/native.go:110 +0x130
main.main()
        /home/runner/work/basenine/basenine/server/server.go:61 +0x51c
```

It's from the [`basenine`](https://github.com/up9inc/basenine) container which is a database server separate than Mizu.

There are probably too many files open on your system. Please try to investigate the root cause or [increase the open file limit](https://unix.stackexchange.com/a/145025/238277).

**Comment by ittaigilat-cx** [comment]
@mertyildiran thanks for your response. I increased the **`nofiles`** limit (`ulimit -n`) to 1048576 (from 1024) but I still get the same "too many open files" message in the `basenine` container. Could be that the basenine container is limiting the basenine server? What else can I try?

**Comment by mertyildiran** [comment]
@ittaigilat-cx how many users simultaneously use Mizu? Because each ongoing query stream maintains an open file in Basenine. Although the error happens in the very beginning of the program:

https://github.com/up9inc/basenine/blob/main/server/server.go#L61

*(which means Basenine database server is not even started to listen for connections)*

Cloud there be hanging processes of Basenine or Mizu *(or an unrelated binary)* that occupies open file slots in the system?

Is it possible for you to consistently reproduce the error? If so, could you please provide the details to reproduce the error?
